import type { ConsumptionProfile, EnergyAnomaly, Recommendation } from "@/lib/intelligence/types";

export function generateRecommendations(profile: ConsumptionProfile, anomalies: EnergyAnomaly[]): Recommendation[] {
  const items: Recommendation[] = [];
  if (profile.type === "night-waste" || profile.type === "continuous-load") items.push({ id: "base-load", title: "Reduce non-operational base load", description: "Apply shutdown schedules to lighting, plug loads and ventilation outside occupied hours.", impactScore: 92, effortScore: 28, confidence: 0.91, estimatedAnnualSavingsKwh: 18400, estimatedAnnualSavingsCost: 4416, paybackMonths: 4, rationale: ["Elevated overnight demand", "Stable controllable base load"] });
  if (profile.type === "peak-heavy") items.push({ id: "peak-shaving", title: "Sequence high-load equipment", description: "Stagger equipment startup and defer flexible loads outside the demand peak window.", impactScore: 86, effortScore: 42, confidence: 0.88, estimatedAnnualSavingsKwh: 9700, estimatedAnnualSavingsCost: 3650, paybackMonths: 7, rationale: ["High peak-to-average ratio", "Demand-charge exposure"] });
  if (profile.type === "irregular") items.push({ id: "schedule-control", title: "Standardize operating schedules", description: "Align equipment schedules with occupancy and flag manual overrides that remain active.", impactScore: 74, effortScore: 31, confidence: 0.79, estimatedAnnualSavingsKwh: 8200, estimatedAnnualSavingsCost: 1968, paybackMonths: 5, rationale: ["Irregular operating pattern", "High short-term variance"] });
  if (anomalies.some((item) => item.severity === "high")) items.push({ id: "investigate-anomaly", title: "Investigate critical consumption spikes", description: "Review the affected zones and compare equipment state, schedule overrides and maintenance history.", impactScore: 95, effortScore: 18, confidence: 0.94, estimatedAnnualSavingsKwh: 12600, estimatedAnnualSavingsCost: 3024, paybackMonths: 2, rationale: ["Critical anomaly detected", `${anomalies.filter((item) => item.severity === "high").length} high-severity events`] });
  if (!items.length) items.push({ id: "tariff-window", title: "Shift flexible loads to lower-cost hours", description: "Move non-critical charging and thermal loads into off-peak tariff windows.", impactScore: 68, effortScore: 24, confidence: 0.76, estimatedAnnualSavingsKwh: 4100, estimatedAnnualSavingsCost: 1480, paybackMonths: 3, rationale: ["Stable demand profile", "Available scheduling flexibility"] });
  return items.sort((a, b) => b.impactScore - a.impactScore);
}
