"use client";
import Link from "next/link";
import { Building2, Gauge, MapPin, Search, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { buildings } from "@/data/assets";
import { Input } from "@/components/ui/input";
import { StatusBadge } from "@/components/ui/status-badge";
export function BuildingCards(){const [query,setQuery]=useState("");const [status,setStatus]=useState("All");const filtered=useMemo(()=>buildings.filter(b=>(status==="All"||b.status===status)&&`${b.name} ${b.code} ${b.type}`.toLowerCase().includes(query.toLowerCase())),[query,status]);return <>
 <div className="flex flex-col gap-3 rounded-2xl border bg-card p-3 sm:flex-row sm:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Search buildings, code or type" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="flex gap-2 overflow-x-auto">{["All","Operational","Optimization","Maintenance"].map(v=><button key={v} onClick={()=>setStatus(v)} className={`rounded-xl px-3 py-2 text-xs font-medium transition ${status===v?"bg-foreground text-background":"bg-muted text-muted-foreground hover:text-foreground"}`}>{v}</button>)}</div></div>
 <div className="grid gap-4 md:grid-cols-2">{filtered.map(b=><Link href={`/dashboard/buildings/${b.id}`} key={b.id} className="group rounded-3xl border bg-card p-5 transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-lg"><div className="flex items-start justify-between"><div className="flex size-11 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Building2 className="size-5"/></div><StatusBadge status={b.status}/></div><h2 className="mt-5 text-lg font-semibold">{b.name}</h2><p className="mt-1 text-sm text-muted-foreground">{b.code} · {b.type}</p><p className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><MapPin className="size-3.5"/>{b.address}</p><div className="mt-5 grid grid-cols-3 gap-2 border-t pt-4 text-sm"><Metric icon={<Gauge/>} value={`${b.efficiency}%`} label="Efficiency"/><Metric icon={<Users/>} value={b.occupancy.toLocaleString()} label="Occupancy"/><Metric icon={<Building2/>} value={`${b.floors} / ${b.zones}`} label="Floors / zones"/></div></Link>)}</div>
 </>}
function Metric({icon,value,label}:{icon:React.ReactElement;value:string;label:string}){return <div><div className="flex items-center gap-1.5 text-foreground [&_svg]:size-3.5 [&_svg]:text-primary"><span>{icon}</span><strong>{value}</strong></div><p className="mt-1 text-[11px] text-muted-foreground">{label}</p></div>}
